apiVersion: v1
kind: Service
metadata:
  annotations:
    # omni-kube-service-exposer.sidero.dev/label: n8n
    # omni-kube-service-exposer.sidero.dev/port: "3008"
  name: n8n
  namespace: n8n
spec:
  ports:
    - port: 3008
  selector:
    app: n8n
  type: ClusterIP
