apiVersion: v1
data:
  password: ENC[AES256_GCM,data:TcZ2tf7iKT8vyh5Q,iv:Feyel0wXSDDFTkln/rodj1tLL46mIfKtxUSRwl9gs9o=,tag:Cv4D78EAfWzNqjxbKTJGCQ==,type:str]
kind: Secret
metadata:
  name: pgadmin-secret
sops:
  age:
    - recipient: age1qc420n98ky2yq9x0j4v7ea9tdvyn9dtr704dd2x59vgy8tswc9qsayz2v5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWHpFZmRlNGxKR3g4NUVa
        T1M5Wm1NUzBDalZUTGd4MUdteTE1RTdZbmlBCk40NGxFSjNjbHBKTndOaW5EMEZm
        NlplTE1ES1VhWVNYWFRDZGloY25qU2cKLS0tIC9mRE5XV3R5R21ET0EvUkJGWW1Y
        ODVyWnRyL3hSS0xvNG9JUDExOWc1STgKKX/RkulNIZC190CfcaPxCfG88AT392RG
        6Wt8icqkJX4ZZp20Ru+L0Izqjq/m2+Ay5yiuSsWVMBZSwnnQLftwzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T15:04:00Z"
  mac: ENC[AES256_GCM,data:HuDTUx9rUuUGrIW5P2T9mQpuhJeva2atBt+7X/PIWstaU/P9MmZmU+NBy90kB/OvVm8xMDno67DxX0RFxskxakkT16FxVfmr1UublJ+VQuu5u86d6aqz10cC9sztBUyfd1PKfdmHaBR+fhlDMygKUtQn5+loSra310SV+RHG5y8=,iv:dqgkDRDpYsqFo/ekp0HYFHlcBPmXpo9pIOoTGbwe0vE=,tag:BxdmrHeZAtgjwGKu/4qXHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
