apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:E52oZOEvrrcTZeHt43BhGjyhlNiD9zX0s1pvhcIjGqoZrRzE0KkCyhKLI57h0qZLMX19S/2EhbeVgj3p58yRP+733Y1EsV0qXqNcmTAZ6pXdumYrdvV2y3JEB5SUnzi2wpjbXeP0Smfw0/k+0qiSB2m5q6HXyjbOMZjCGmH6BjnN3iaV7QIZ/gUaaSQquwug7FHYH2Je5KNNqia5I9pBag3YAZN7uL9akINcJCAvET2lYyc1Q1uNQ5GEdP+eASdVq7as/Bz8Sdbfvhkl/x8549XjXPIhydPUIwCfamZDgx98QmWeU6UbwB6oVDU=,iv:v/1DqPlrMoiJqS3puDuXJiLWef3TFQxBzDek38EZswo=,tag:Bk9V48suLEcASCKaynTmkQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: linkding
sops:
  age:
    - recipient: age1qc420n98ky2yq9x0j4v7ea9tdvyn9dtr704dd2x59vgy8tswc9qsayz2v5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeFdRT1FxTU9tL0I0c2ps
        WUxlSjloaXUvVTVjRU1sZzQrTWVvK0FRNjFBClJET0w4ditITktKNlRGZU14Ny9K
        MVY1MzQ1UGNtdlozV2UrZTM1VVJSNVEKLS0tIEpBVVJGNkc3ajY2ZEZrTENaN3gr
        Mmt5anRDb0thekx3NFV1a0pNSlNRcUEKzGlN7zKhzmlakjcQeX9DT6nkXisoD/Wj
        KQHxBJHwywEe5wkp4uiF9uzYsUelX+V57WrIfIbOQ1udY6cvIuNfkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-17T14:51:14Z"
  mac: ENC[AES256_GCM,data:03jpXHRqshU0iigZn2oe+49XMTuonlJRxuEG+2w5SVT2y4XpuF7AZgrhCDj/2POZG8yW79xL3H2JHuVIgmcyJTliVIakUFcBwuHFrTDGkmFVR56cbCTpdK4GCMyW55pqBeh7AZeq8OdCupCCjr4jRYRdhUtrMKFZ6xiaflLcK88=,iv:eGo6PPh0ENKUGOozVjeJAX8yWUR0xMV+NyYJewnmY9w=,tag:2XfVbXWdVKBrcnSHjlmzeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
