apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:cdmmRNOTv5qmzb4hprmY/GSHR7rfe/HEkEUoHNSdH//gR0tAc9hJ75oGoLPLb+pxGZqtqlnB/A/vTioaelqJBFHqW3m5o6Lvlm0NExm/gphxFcWDkQaGs0alyFwxgWtEmzBdAnDmLRe1sRQSlDuemWiMnnu2zKCzsOSYpFSm2TlbWblred1LHD+8UvuGWHT9w1DvwbYYho3rScIXKhZcqYq+JXOddJokWLeOcLrcDz84FBjXk+ldgVm7iVGD10004mmhbEyCO45/JNIykcguAmq5PfoZveHHjuc6cU3xhsFvahs8S8c0HQROOfg=,iv:vAr1+USnEhELjO0ttItcSu7fqS2+PGrHcyfrO6KL+Xg=,tag:wKfKagQOLeWWO625yvRHrw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1qc420n98ky2yq9x0j4v7ea9tdvyn9dtr704dd2x59vgy8tswc9qsayz2v5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVmM0N250eUhoYUFnK3RC
            ellDQ24zR1prTTUvemFBUERLWXpzOTh6RENRCmh6d25WbE5oTXMvaFVBUGo2ZWw4
            S09SdzdrRktNWStUOCtsaTh4ZWR4cW8KLS0tIFFZeUVZQmJKRUpVU0c4bGxKcW5i
            NWk2aE9ZNU5DQmdDd1ZUQ01CTVNPNkUKI7QVKfvemSbE1YZiFRtVDh4MnZTTDgjL
            koe7YDckShtFWVznO/kj1jRte9Dq3byTkWzLJx8IlOvlLTpKR3CMIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T04:24:53Z"
    mac: ENC[AES256_GCM,data:5oZx9WVr+3gIx00GKS/zVeOBCvuJj2zUpwa8gqvjvK3Y+YKVUS/ZPgH9P9V1VfTyi6mSsjxz+HY25T7fKl1JYb2tRzT2zLdw20ZnOmC0co9FJdXwFOqJZsTZqRDYp9Qi4wW+/vZgbp2yQpdB54PQDiE0SckT4/iHlI20OfLcy0g=,iv:CNn3RwIpwl29YFKgxUeABjqi8vvc+yb//FyrB1MeI1M=,tag:3FmuYTk+b0fPTsQJiJsKYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
