apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  # namespace: linkding
spec:
  ingressClassName: traefik
  rules:
    - host: n8n.abdulshukor.org
      http:
        paths:
          - backend:
              service:
                name: n8n
                port:
                  number: 3008
            path: /
            pathType: Prefix
