apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  # All resources loaded through this kustomizion file and will all loaded in namespace n8n
  # Set namespace at this level
  - ../../base/n8n/
  - cloudflare.yaml
  - cloudflare-n8n-secret.yaml
  # - linkding-container-env-secret.yaml
  # - ingress.yaml
